#!/bin/tcsh -f

# copy and paste from
# echo $DYLD_LIBRARY_PATH

setenv DYLD_LIBRARY_PATH /opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/evio/5.1/lib:/opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/mlibrary/1.5/lib:/opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/ccdb/ccdb-1.07.00/lib:/opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/root/6.24.06/lib/root:/opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/root/6.24.06/lib:/opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/geant4/4.10.07.p03/lib:/opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/qt/system/clang_64/lib:/opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/xercesc/3.2.3/lib:/opt/jlab_software/2.5/Darwin_macosx12.6-clang14.0.0/clhep/2.4.4.2/lib:
gemc -help-html ; mv options.html allOptions.html
