#!/bin/tcsh -f

# looks like there is no way around this, must sent env or script won't find env?

#setenv JLAB_VERSION 2.2
#source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh keepmine

# looks like setting DYLD_LIBRARY_PATH is enough. But gemc is found, how?

setenv DYLD_LIBRARY_PATH /opt/jlab_software/2.2/Darwin_macosx10.13-x86_64-clang9.0.0/root/6.12.06/lib/root:/opt/jlab_software/2.2/Darwin_macosx10.13-x86_64-clang9.0.0/root/6.12.06/lib:/opt/jlab_software/2.2/Darwin_macosx10.13-x86_64-clang9.0.0/qt/5.9.1/5.9.1/clang_64/lib:/opt/jlab_software/2.2/Darwin_macosx10.13-x86_64-clang9.0.0/mysql/lib:/opt/projects/mlibrary/lib:/opt/jlab_software/2.2/Darwin_macosx10.13-x86_64-clang9.0.0/geant4/4.10.03.p02/lib:/opt/jlab_software/2.2/Darwin_macosx10.13-x86_64-clang9.0.0/evio/5.1/lib:/opt/jlab_software/2.2/Darwin_macosx10.13-x86_64-clang9.0.0/clhep/2.3.4.5/lib:/opt/jlab_software/2.2/Darwin_macosx10.13-x86_64-clang9.0.0/ccdb/ccdb-1.06.02/lib:/opt/projects/banks/lib:

gemc -help-html ; mv options.html allOptions.html
