#!/bin/tcsh -f

# looks like there is no way around this, must sent env or script won't find env?

#setenv JLAB_VERSION 2.2
#source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh keepmine

# looks like setting DYLD_LIBRARY_PATH is enough. But gemc is found, how?
# not needed in path: root, banks.
# copy and paste from
# echo $DYLD_LIBRARY_PATH

setenv DYLD_LIBRARY_PATH /opt/jlab_software/devel/Darwin_macosx10.14-x86_64-clang11.0.0/mysql/lib:/opt/jlab_software/devel/Darwin_macosx10.14-x86_64-clang11.0.0/evio/5.1/lib:/opt/jlab_software/devel/Darwin_macosx10.14-x86_64-clang11.0.0/xercesc/3.2.2/lib:/opt/projects/mlibrary/lib:/opt/jlab_software/devel/Darwin_macosx10.14-x86_64-clang11.0.0/ccdb/ccdb-1.06.02/lib:/opt/jlab_software/devel/Darwin_macosx10.14-x86_64-clang11.0.0/qt/system/clang_64/lib:/opt/jlab_software/devel/Darwin_macosx10.14-x86_64-clang11.0.0/geant4/4.10.05.p01/lib:/opt/jlab_software/devel/Darwin_macosx10.14-x86_64-clang11.0.0/clhep/2.4.1.0/lib:
gemc -help-html ; mv options.html allOptions.html
