#!/bin/csh -f

rm -f *.tar


foreach d (atlas forFun humanBody)
	cd $d
	rm -rf *
	cp -r /opt/projects/gemc/detectors/$d .
	tar cvf $d.tar *
	mv $d.tar ..
	cd ..
end


foreach d (exampleCTOFCAD exampleCentralTOF)
	cd $d
	tar cvf $d.tar *
	mv $d.tar ..
	cd ..
end

scp *.tar ftp.jlab.org:/group/clas/www/gemc/html/gemc/html/documentation/tutorials/material/

rm -f *.tar
