#!/bin/csh -f

rm -f *.tar

foreach d (atlas forFun humanBody)
	rm -rf $d
	cp -r /opt/projects/gemc/detectors/$d .
	tar cvf $d.tar $d
end


foreach d (exampleCTOFCAD exampleCentralTOF)
	tar cvf $d.tar $d
end

tar cvf myFirst.tar myFirst

scp *.tar ifarm:/group/clas/www/gemc/html/gemc/html/documentation/tutorials/material/

rm -f *.tar
