#!/bin/csh 

# MacPro cronjob:
# 35 04 * * * /opt/projects/gemc/docs/doxygen/go_gemc_doxygen

if($#argv != 1) then
    echo " "
    echo "Usage:   "
    echo  "  >> go_gemc_doxygen <version>"
    echo
    echo "      versions can be 'all' "
    exit 0
endif



set cdir = /opt/projects/gemc/docs/doxygen

# make sure we have all versions
rm -rf   gemc_doxy
mkdir -p gemc_doxy
cd       gemc_doxy

git clone https://github.com/gemc/releases.git
cd releases

set versions = $1

if($versions == "all") then
    set versions = `\ls`
endif

echo
echo DOXYGEN for versions: $versions
echo

foreach v ($versions)
	echo
	echo Running $v
	cd $v
	cp $cdir/Doxyfile .
	echo "PROJECT_NUMBER=$v" >> Doxyfile
	doxygen Doxyfile

	# moving it first, then copying, so I can omit
	# destination filename, otherwise may put it
	# in sub-dir (e.g. 2.0_beta1/2.0_beta1)
	mv html $v
	cp $cdir/gemc_logo.gif $v

	scp -r $v ftp:/u/group/clas/www/gemc/html/work/doxy

	cd ../
end

# main mage
cd $cdir
scp gemc_logo.gif ftp:/u/group/clas/www/gemc/html/work/doxy
scp doxies.html   ftp:/u/group/clas/www/gemc/html/work/doxy
scp table.css     ftp:/u/group/clas/www/gemc/html/work/doxy

